language: node_js
node_js:
  - lts/*

branches:
  only:
    - gh-pages

env:
  global:
    - URL="http://w3c.github.io/push-api/echidna-manifest.txt"
    - DECISION="https://github.com/w3c/push-api/issues/241"
    - secure: "I4v5gVO1ONjLjyFZQe7b0NCbmXIMOgd/+0jqLeFrkp4cKLXhfkphbqIBDvb6tmxa90dfCYKswM4L0EiMlBu8EYtKwvmSQXoeOLpBoyZDy2BsgQcrb7L/FKMr/AHDId/D6GZVxOhkoT5d129nN4Cf66cRWEFZtR3RJE2Xq13HrT4="
install:
  - npm install respec-validator

script:
  - npx respec-validator --manifest=ECHIDNA --check-links-using-get --gh-user=$GH_USER --gh-token=$GH_TOKEN index.html

cache:
  directories:
    - node_modules

after_success:
  - echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
  - CC="mcaceres@mozilla.com"
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"  --data "cc=$CC"
